name: environment-deep-learning-cookbook
channels:
    - https://conda.anaconda.org/menpo
    - conda-forge
dependencies:
    - python==3.5.2
    - numpy
    - pandas
    - scikit-learn
    - matplotlib
    - jupyter
    - opencv3
